### ISSUE TITLE
Fullscreen and resolution settings don't save unless you do something in game that forces an update

### ISSUE THREAD

**Issue by darkscott** [corfe83/IdleArmadaIssues#154]
If you change a setting in the settings window, then close the window, the settings will not be saved.

Even if you click export the save file, the settings won't be saved.

If you buy something on another screen, it will save the settings.

Expected: When you change a setting, the save is updated immediately.

**Comment by corfe83** [comment]
After looking at this, I realized something.

Most settings DO save automatically. For example, "sound", "battery saving FPS", "stop drawing health bars", all of those save immediately when you click them.

The only settings that DO NOT save are when toggling fullscreen/windowed mode, and when toggling resolution. And this was an intentional choice, because I don't have UI to say "are you still able to see the screen after changing resolution?". Basically, if some wonky graphics card driver leaves their game window totally unusable or something after changing to fullscreen, I don't save it on their save and leave them permanently that way. They'll have to buy a building or something to "confirm" they can still see the screen.

I've renamed the title to reflect that the way to fix this is to add that sort of "can you still see this?" UI dialog.

**Comment by corfe83** [comment]
This is now fixed, there is a confirmation dialog
