### ISSUE TITLE
Active play has too small benefit when playing in end-game

### ISSUE THREAD

**Issue by darkscott** [corfe83/IdleArmadaIssues#166]
The game basically goes full idle at the end-game.  

This is probably going to be an issue regardless of what other active mechanics are (probably) going to be introduced.

Most items scale damage based on ship damage, and ship damage is limited at high levels by income (metal, crystal, gold).  This means that the effect of collecting items decreases as you get higher.  Simultaneous with this, the drop rate of items is considerably lower at high levels because you aren't killing as much per minute, and there are more ships).

There should probably be some mechanic, inversely proportional to kill rate, that gives some benefit to actively playing in the end game.  Ideas to consider: Additional resource drops, chance to drop additional items without a kill taking place, special ship spawns that must be manually targeted that drop current Mark + 2 items, etc.

**Comment by corfe83** [comment]
Fixed in 0.15.0.0 -- there are now resource drops on battle screen to click on (at random time intervals rather than when ships are destroyed), and also there are active abilities that when used increase your exp/gold farm rate, or can help you push to a new level (which gets you land, which may also help your exp/gold farm rate)
